name: "cdxgen"
description: "Generate CycloneDX BOM xml file using cdxgen tool for supported projects"
inputs:
  output:
    description: "Output file for bom.xml. Default console"
    required: true
  projectId:
    description: "Dependency track or AppThreat project id. Either provide the id or the project name and version together"
    required: false
  projectName:
    description: "Dependency track or AppThreat project name. Default use the repo name"
    required: false
  projectVersion:
    description: "Dependency track or AppThreat project version. Default repo branch"
    required: false
  serverUrl:
    description: "Dependency track or AppThreat server url. Eg: https://deptrack.appthreat.io"
    required: false
  apiKey:
    description: "Dependency track or AppThreat server api key. Use secrets to inject this value"
    required: false
outputs:
  token:
    description: "Server token to query for status"
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "check"
  color: "blue"
